export interface BibleBook {
  id: string;
  bibleId: string;
  abbreviation: string;
  name: string;
  nameLong: string;
}

export const bibleBooks = [
  {
    id: "GEN",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "gn",
    name: "Gênesis",
    nameLong: "O Livro de Gênesis",
  },
  {
    id: "EXO",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ex",
    name: "Êxodo",
    nameLong: "O Livro de Êxodo",
  },
  {
    id: "LEV",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "lv",
    name: "Levítico",
    nameLong: "O Livro de Levítico",
  },
  {
    id: "NUM",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "nm",
    name: "Números",
    nameLong: "O Livro de Números",
  },
  {
    id: "DEU",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "dt",
    name: "Deuteronômio",
    nameLong: "O Livro de Deuteronômio",
  },
  {
    id: "JOS",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "js",
    name: "Josué",
    nameLong: "O Livro de Josué",
  },
  {
    id: "JDG",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jz",
    name: "Juízes",
    nameLong: "O Livro de Juízes",
  },
  {
    id: "RUT",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "rt",
    name: "Rute",
    nameLong: "O Livro de Rute",
  },
  {
    id: "1SA",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1sm",
    name: "1º Samuel",
    nameLong: "O Primeiro Livro de Samuel",
  },
  {
    id: "2SA",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2sm",
    name: "2º Samuel",
    nameLong: "O Segundo Livro de Samuel",
  },
  {
    id: "1KI",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1rs",
    name: "1º Reis",
    nameLong: "O Primeiro Livro dos Reis",
  },
  {
    id: "2KI",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2rs",
    name: "2º Reis",
    nameLong: "O Segundo Livro dos Reis",
  },
  {
    id: "1CH",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1cr",
    name: "1º Crônicas",
    nameLong: "O Primeiro Livro das Crônicas",
  },
  {
    id: "2CH",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2cr",
    name: "2º Crônicas",
    nameLong: "O Segundo Livro das Crônicas",
  },
  {
    id: "EZR",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ed",
    name: "Esdras",
    nameLong: "O Livro de Esdras",
  },
  {
    id: "NEH",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ne",
    name: "Neemias",
    nameLong: "O Livro de Neemias",
  },
  {
    id: "EST",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "et",
    name: "Ester",
    nameLong: "O Livro de Ester",
  },
  {
    id: "JOB",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jó",
    name: "Jó",
    nameLong: "O Livro de Jó",
  },
  {
    id: "PSA",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "sl",
    name: "Salmos",
    nameLong: "O Livro dos Salmos",
  },
  {
    id: "PRO",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "pv",
    name: "Provérbios",
    nameLong: "O Livro de Provérbios",
  },
  {
    id: "ECC",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ec",
    name: "Eclesiastes",
    nameLong: "O Livro de Eclesiastes",
  },
  {
    id: "SNG",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ct",
    name: "Cânticos",
    nameLong: "O Cântico dos Cânticos de Salomão",
  },
  {
    id: "ISA",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "is",
    name: "Isaías",
    nameLong: "O Livro do Profeta Isaías",
  },
  {
    id: "JER",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jr",
    name: "Jeremias",
    nameLong: "O Livro do Profeta Jeremias",
  },
  {
    id: "LAM",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "lm",
    name: "Lamentações",
    nameLong: "As Lamentações de Jeremias",
  },
  {
    id: "EZK",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ez",
    name: "Ezequiel",
    nameLong: "O Livro do Profeta Ezequiel",
  },
  {
    id: "DAN",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "dn",
    name: "Daniel",
    nameLong: "O Livro do Profeta Daniel",
  },
  {
    id: "HOS",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "os",
    name: "Oséias",
    nameLong: "O Livro do Profeta Oséias",
  },
  {
    id: "JOL",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jl",
    name: "Joel",
    nameLong: "O Livro do Profeta Joel",
  },
  {
    id: "AMO",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "am",
    name: "Amós",
    nameLong: "O Livro do Profeta Amós",
  },
  {
    id: "OBA",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ob",
    name: "Obadias",
    nameLong: "O Livro do Profeta Obadias",
  },
  {
    id: "JON",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jn",
    name: "Jonas",
    nameLong: "O Livro do Profeta Jonas",
  },
  {
    id: "MIC",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "mq",
    name: "Miquéias",
    nameLong: "O Livro do Profeta Miquéias",
  },
  {
    id: "NAM",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "na",
    name: "Naum",
    nameLong: "O Livro do Profeta Naum",
  },
  {
    id: "HAB",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "hc",
    name: "Habacuque",
    nameLong: "O Livro do Profeta Habacuque",
  },
  {
    id: "ZEP",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "sf",
    name: "Sofonias",
    nameLong: "O Livro do Profeta Sofonias",
  },
  {
    id: "HAG",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ag",
    name: "Ageu",
    nameLong: "O Livro do Profeta Ageu",
  },
  {
    id: "ZEC",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "zc",
    name: "Zacarias",
    nameLong: "O Livro do Profeta Zacarias",
  },
  {
    id: "MAL",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ml",
    name: "Malaquias",
    nameLong: "O Livro do Profeta Malaquias",
  },
  {
    id: "MAT",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "mt",
    name: "Mateus",
    nameLong: "O Evangelho Segundo Mateus",
  },
  {
    id: "MRK",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "mc",
    name: "Marcos",
    nameLong: "O Evangelho Segundo Marcos",
  },
  {
    id: "LUK",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "lc",
    name: "Lucas",
    nameLong: "O Evangelho Segundo Lucas",
  },
  {
    id: "JHN",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jo",
    name: "João",
    nameLong: "O Evangelho Segundo João",
  },
  {
    id: "ACT",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "at",
    name: "Atos",
    nameLong: "Atos dos Apóstolos",
  },
  {
    id: "ROM",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "rm",
    name: "Romanos",
    nameLong: "A Carta de Paulo aos Romanos",
  },
  {
    id: "1CO",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1co",
    name: "1ª Coríntios",
    nameLong: "A Primeira Carta de Paulo aos Coríntios",
  },
  {
    id: "2CO",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2co",
    name: "2ª Coríntios",
    nameLong: "A Segunda Carta de Paulo aos Coríntios",
  },
  {
    id: "GAL",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "gl",
    name: "Gálatas",
    nameLong: "A Carta de Paulo aos Gálatas",
  },
  {
    id: "EPH",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ef",
    name: "Efésios",
    nameLong: "A Carta de Paulo aos Efésios",
  },
  {
    id: "PHP",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "fp",
    name: "Filipenses",
    nameLong: "A Carta de Paulo aos Filipenses",
  },
  {
    id: "COL",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "cl",
    name: "Colossenses",
    nameLong: "A Carta de Paulo aos Colossenses",
  },
  {
    id: "1TH",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1ts",
    name: "1ª Tessalonicenses",
    nameLong: "A Primeira Carta de Paulo aos Tessalonicenses",
  },
  {
    id: "2TH",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2ts",
    name: "2ª Tessalonicenses",
    nameLong: "A Segunda Carta de Paulo aos Tessalonicenses",
  },
  {
    id: "1TI",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1tm",
    name: "1ª Timóteo",
    nameLong: "A Primeira Carta de Paulo a Timóteo",
  },
  {
    id: "2TI",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2tm",
    name: "2ª Timóteo",
    nameLong: "A Segunda Carta de Paulo a Timóteo",
  },
  {
    id: "TIT",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "tt",
    name: "Tito",
    nameLong: "A Carta de Paulo a Tito",
  },
  {
    id: "PHM",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "fm",
    name: "Filemom",
    nameLong: "A Carta de Paulo a Filemom",
  },
  {
    id: "HEB",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "hb",
    name: "Hebreus",
    nameLong: "A Carta aos Hebreus",
  },
  {
    id: "JAS",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "tg",
    name: "Tiago",
    nameLong: "A Carta de Tiago",
  },
  {
    id: "1PE",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1pe",
    name: "1ª Pedro",
    nameLong: "A Primeira Carta de Pedro",
  },
  {
    id: "2PE",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2pe",
    name: "2ª Pedro",
    nameLong: "A Segunda Carta de Pedro",
  },
  {
    id: "1JN",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "1jo",
    name: "1ª João",
    nameLong: "A Primeira Carta de João",
  },
  {
    id: "2JN",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "2jo",
    name: "2ª João",
    nameLong: "A Segunda Carta de João",
  },
  {
    id: "3JN",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "3jo",
    name: "3ª João",
    nameLong: "A Terceira Carta de João",
  },
  {
    id: "JUD",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "jd",
    name: "Judas",
    nameLong: "A Carta de Judas",
  },
  {
    id: "REV",
    bibleId: "90799bb5b996fddc-01",
    abbreviation: "ap",
    name: "Apocalipse",
    nameLong: "O Apocalipse de João",
  },
];
